Added compatibility for 306 firmware

diff --git a/patch-airsense b/patch-airsense
--- a/patch-airsense
+++ b/patch-airsense
@@ -20,9 +20,15 @@ patch() {
 	dd bs=1 seek=$offset conv=notrunc of="$OUT" status=none
 }
 
-echo "533b91127aa22e05b933db203ad56c449dc12a8c3fd62f57bd88c472a8061775  $IN"\
-| sha256sum --check \
-|| die "$IN: wrong hash"
+shasum=$( sha256sum $IN | cut -f 1 -d " " )
+if [ $shasum = "533b91127aa22e05b933db203ad56c449dc12a8c3fd62f57bd88c472a8061775" ]; then
+	version="401"
+elif [ $shasum = "363a204ba217f31223e929365d58b8f5ce038a7681e362fe157e190c2eacbd30" ]; then
+	version="306"
+else
+	die "$IN: incompatible firmware version."
+fi
+echo "Found firmware version: $version"
 
 cp "$IN" "$OUT" || die "$OUT: copy failed"
 
@@ -40,10 +46,12 @@ BUILD_FLAGS=0
 patch_code() {
 	#if you want to add the extra breath mode
 	BUILD_FLAGS=$(( BUILD_FLAGS | (1 << 0) ))
-
-	if [ -r breath.bin ] ; then
+	if [ -r breath.bin ] && [ $version = "401" ] ; then
 		echo "Including breath.bin"
 		cat breath.bin | patch 0xbb734 || die "binary patch failed"
+	elif [ -r breath.bin ] && [ $version = "401" ] ; then
+                echo "Including breath.bin"
+                cat breath.bin | patch 0xbb4d4 || die "binary patch failed"
 	else
 		die "breath.bin not found, did you run make?"
 	fi 
